# // import { gql } from '../../../node_modules/apollo-server/src/exports.ts'
# // import { gql } from'apollo-server-core'
#  import gql  from '../../gql.mjs'
# // import gql from 'gql-tag'
# // const { gql } = gql
# // export const AirlinerTypeDefs = gql`
# export const AirlinerTypeDefs = `

  """
    Airliner represents an airline company.
  """
  input AirlinerInput {
    _id: UUID
    airlinerName: String
    ceatedAt: Date
    modelAircraft: [{modelAircraft: [String]}]
  }

  type Airliner {
    _id: ID!
    airlinerName: String
    isAdmin: Boolean
    modelAircraft: [String]
    email: String
    password: String
  }

    """
    Get an airliner by ID.
    """
    """
    Get airliners by airliner name.
    """
  type Query {
    airliner(_id: ID!): Airliner

    airliners(airlinerName: String): [Airliner]
  }

    """
    Add a new airliner.
    """

    """
    Remove an existing airliner.
    """
  type Mutation {
    addAirliner(
      airlinerName: String
      _isAdmin: Boolean
      modelAircraft: [String]
      email: String
      password: String
    ): Airliner
    removeAirliner(_id: ID!): Boolean
  }
;

console.log(AirlinerInput)